In [44]:
import kagglehub
import pandas as pd

path = kagglehub.dataset_download("clmentbisaillon/fake-and-real-news-dataset")

true_df = pd.read_csv(path + '/True.csv')
fake_df = pd.read_csv(path + '/Fake.csv')

print("Path to dataset files:", path)

Path to dataset files: /home/jens/.cache/kagglehub/datasets/clmentbisaillon/fake-and-real-news-dataset/versions/1

In [45]:
true_df.describe()

,title,text,subject,date
count,21417,21417,21417,21417
unique,20826,21192,2,716
top,Factbox: Trump fills top jobs for his administ...,(Reuters) - Highlights for U.S. President Dona...,politicsNews,"December 20, 2017"
freq,14,8,11272,182

In [46]:
true_df.sample(5, random_state=42)

,title,text,subject,date
18137,Canada government facing resistance from Senat...,OTTAWA (Reuters) - The Canadian government s p...,worldnews,"November 3, 2017"
3277,London will remain leading financial center: P...,LONDON (Reuters) - London will remain the worl...,worldnews,"October 19, 2017"
2876,Britain preparing to transfer 400 million poun...,LONDON (Reuters) - Britain is preparing to tra...,worldnews,"November 16, 2017"
5160,Merkel's conservatives tied with SPD ahead of ...,BERLIN (Reuters) - German Chancellor Angela Me...,worldnews,"October 2, 2017"
10843,U.S. vice presidential debate watched by 37 mi...,NEW YORK (Reuters) - An estimated 37 million A...,politicsNews,"October 5, 2016"

In [47]:
fake_df.sample(5, random_state=42)

,title,text,subject,date
13474,ABOUT HILLARY’S COUGH: We Discovered The Secre...,,politics,"Jul 20, 2016"
11994,BREAKING: OBAMACARE REPEAL Clears First Hurdle...,The Senate voted 51-48 this afternoon to proce...,politics,"Jan 4, 2017"
19179,‘SLEEPY’ JUSTICE GINSBURG: Excites Crowd By Sa...,So much for the SCOTUS not being political Che...,left-news,"Feb 7, 2017"
501,WATCH: Kellyanne Conway Very Upset Hillary Cl...,White House counselor Kellyanne Conway crawled...,News,"August 24, 2017"
3492,"GOP Gives Trump The Middle Finger, Prepares T...",Donald Trump may have decided that Russia is g...,News,"December 9, 2016"

In [70]:
# Combine datasets
fake_df['is_fake'] = 1
true_df['is_fake'] = 0

df = pd.concat([fake_df, true_df])

df.sample(5, random_state=42)

,title,text,subject,date,is_fake
22216,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",1
4436,"In shift, Merkel backs end to EU-Turkey member...",BERLIN (Reuters) - German Chancellor Angela Me...,worldnews,"September 3, 2017",0
1526,Trump allies falsely link Reuters to claim Det...,WASHINGTON (Reuters) - Conservative commentato...,politicsNews,"September 6, 2016",0
1377,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",1
8995,Iceland opposition leader says will not rule o...,REYKJAVIK (Reuters) - The leader of Iceland s ...,worldnews,"October 29, 2017",0

In [80]:
# Clean dataset by dropping columns and duplicates
print(df.shape)
clean_df = df.copy().drop(columns = ['title','subject','date'])
clean_df.drop_duplicates(inplace=True)
print(clean_df.shape)
clean_df.sample(5, random_state=42)

(44898, 5)
(38647, 2)

                                                    text  is_fake
18605  CANNON BALL, N.D./WASHINGTON (Reuters) - Three...        0
5873   NAIROBI (Reuters) - In the run-up to Kenya s A...        0
21037  NEW YORK (Reuters) - If Hillary Clinton decide...        0
4132   BEIJING/TAIPEI (Reuters) - Taiwan will fail to...        0
4156   A Pennsylvania man apparently failed basic bio...        1

In [81]:
from sklearn.model_selection import train_test_split

x = clean_df['text'].values
y = clean_df['is_fake'].values

#train, validation, and test split
x_train, x_validation, y_train, y_validation = train_test_split(x, y, test_size=0.3, random_state=42, shuffle=True)
x_validation, x_test, y_validation, y_test = train_test_split(x_validation, y_validation, test_size=0.5, random_state=42, shuffle=True)

len_y_total = len(y_train) + len(y_validation) + len(y_test)
print('train data: ', len(y_train),':', len(y_train)/len_y_total *100 , '% ', 'of total dataset')
print('validation data: ', len(y_validation), ':', len(y_validation) / len_y_total * 100, '% ', 'of total dataset')
print('test data: ', len(y_test),':', len(y_test)/len_y_total *100 , '% ', 'of total dataset')

train data:  27052 : 69.99767122933216 %  of total dataset
validation data:  5797 : 14.999870623851786 %  of total dataset
test data:  5798 : 15.002458146816053 %  of total dataset