In [30]:
from statistics import LinearRegression

import pandas as pd
from sqlalchemy import create_engine

db_user = 'postgres'
db_password = 'postgres'
db_host = 'localhost'
db_port = '5432'
db_name = 'puzzle'

engine = create_engine(f'postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}')

In [31]:
gas_stations_query = """
SELECT * FROM gas_stations
ORDER BY random()
LIMIT 5;
"""
gas_stations_df = pd.read_sql(gas_stations_query, engine)
gas_stations_df.head()

,id,company_name,site,country,city,street_name,house_number,postal_code,lat,lng,is_favorite,created_at,updated_at,location,external_id
0,301,tinq,https://www.tinq.nl/tankstations/breskens-dokw...,NL,Breskens,Dokweg,1,4511 PW,51.391438,3.575661,False,2022-12-30 15:35:35,2023-01-09 15:46:56,0101000020E61000003095C84FF49A0C401C7519A31AB2...,None
1,1000,lukoil,https://forms.lukoil-service.online/stationPag...,NL,GELDROP,Winkelcentrum Coevering,1,5565 GA,51.416756,5.574039,False,2025-07-29 00:33:24,2025-07-29 00:33:24,0101000020E6100000300000E0D04B16404200004058B5...,None
2,541,lukoil,https://forms.lukoil-service.online/stationPag...,BE,ZEVERGEM,Grote Steenweg,16,9840,51.002047,3.691414,False,2023-01-09 15:48:39,2023-01-09 15:48:39,0101000020E6100000ECF82F1004880D4007077B134380...,None
3,280,tinq,https://www.tinq.nl/tankstations/zuilichem-van...,NL,Zuilichem,van Heemstraweg,2,5305 TA,51.800993,5.133459,False,2022-12-30 15:35:35,2023-01-09 15:46:56,0101000020E61000006E6DE179A988144097A949F086E6...,None
4,200,tinq,https://www.tinq.nl/tankstations/raamsdonksvee...,NL,Raamsdonksveer,Elftweg,17,4941 VR,51.711310,4.878791,False,2022-12-30 15:35:34,2023-01-09 15:46:56,0101000020E61000009813B4C9E183134018E9EA330CDB...,None

In [32]:
gas_stations_df.describe()

,id,lat,lng,created_at,updated_at
count,5.000000,5.000000,5.000000,5,5
mean,464.400000,51.464509,4.570673,2023-07-08 22:13:45.400000,2023-07-14 22:20:34.200000
min,200.000000,51.002047,3.575661,2022-12-30 15:35:34,2023-01-09 15:46:56
25%,280.000000,51.391438,3.691414,2022-12-30 15:35:35,2023-01-09 15:46:56
50%,301.000000,51.416756,4.878791,2022-12-30 15:35:35,2023-01-09 15:46:56
75%,541.000000,51.711310,5.133459,2023-01-09 15:48:39,2023-01-09 15:48:39
max,1000.000000,51.800993,5.574039,2025-07-29 00:33:24,2025-07-29 00:33:24
std,325.324915,0.314493,0.891845,NaN,NaN

In [33]:
gas_prices_query = """
SELECT * FROM gas_prices
ORDER BY random()
LIMIT 5;
"""
gas_prices_df = pd.read_sql(gas_prices_query, engine)
gas_prices_df.head()

,id,gas_station_id,fuel_type,price,created_at,updated_at
0,3613829,685,Superplus 98 E5,2139,2025-12-19 18:00:23,2025-12-19 18:00:23
1,2122326,840,Superplus 98 E5,1779,2024-11-10 18:04:21,2024-11-10 18:04:21
2,906193,824,Diesel B7,1639,2023-12-16 18:03:09,2023-12-16 18:03:09
3,51995,377,Diesel B7,1689,2023-01-17 18:00:10,2023-01-17 18:00:10
4,2796221,122,Superplus 98 E5,2069,2025-06-21 18:01:39,2025-06-21 18:01:39

In [34]:
gas_prices_df.describe()

,id,gas_station_id,price,created_at,updated_at
count,5.000000e+00,5.00000,5.000000,5,5
mean,1.898113e+06,569.60000,1863.000000,2024-08-29 13:13:56.400000,2024-08-29 13:13:56.400000
min,5.199500e+04,122.00000,1639.000000,2023-01-17 18:00:10,2023-01-17 18:00:10
25%,9.061930e+05,377.00000,1689.000000,2023-12-16 18:03:09,2023-12-16 18:03:09
50%,2.122326e+06,685.00000,1779.000000,2024-11-10 18:04:21,2024-11-10 18:04:21
75%,2.796221e+06,824.00000,2069.000000,2025-06-21 18:01:39,2025-06-21 18:01:39
max,3.613829e+06,840.00000,2139.000000,2025-12-19 18:00:23,2025-12-19 18:00:23
std,1.431137e+06,311.68622,227.002203,NaN,NaN

In [35]:
# train the model
# Load all data
gas_stations_query = """
SELECT * FROM gas_stations WHERE id = 377;
"""
gas_stations_df = pd.read_sql(gas_stations_query, engine)
gas_stations_df.head()

,id,company_name,site,country,city,street_name,house_number,postal_code,lat,lng,is_favorite,created_at,updated_at,location,external_id
0,377,tango,https://www.tango.nl/stations/tango-haelen,NL,HAELEN,Windmolenbosweg,2,6081 PE,51.222206,5.951285,True,2022-12-30 15:35:36,2025-10-17 23:02:56,0101000020E61000002CA688C21DCE17401F7B6242719C...,202220

In [36]:
# train the model
# Load all data
gas_prices_query = """
SELECT * FROM gas_prices WHERE gas_station_id = 377;
"""
gas_prices_df = pd.read_sql(gas_prices_query, engine)
print(gas_prices_df.count())
gas_prices_df.head()

id                2985
gas_station_id    2985
fuel_type         2985
price             2985
created_at        2985
updated_at        2985
dtype: int64

,id,gas_station_id,fuel_type,price,created_at,updated_at
0,3237268,377,Euro95 E10,1899,2025-10-20 18:00:13,2025-10-20 18:00:13
1,3237269,377,Superplus 98 E5,2189,2025-10-20 18:00:13,2025-10-20 18:00:13
2,3237270,377,Diesel B7,1649,2025-10-20 18:00:13,2025-10-20 18:00:13
3,1132,377,Euro95 E10,1739,2022-12-31 18:00:04,2022-12-31 18:00:04
4,1133,377,Superplus 98 E5,2009,2022-12-31 18:00:04,2022-12-31 18:00:04

In [37]:
x = gas_prices_df[["gas_station_id", "fuel_type", "created_at"]].copy()
x = pd.get_dummies(x, columns=["fuel_type", "gas_station_id"])

x["created_at"] = pd.to_datetime(x["created_at"])
x["year"] = x["created_at"].dt.year
x["month"] = x["created_at"].dt.month
x["day"] = x["created_at"].dt.day
x = x.drop(columns=["created_at"])

x.head()

,fuel_type_Diesel B7,fuel_type_Euro95 E10,fuel_type_Superplus 98 E5,gas_station_id_377,year,month,day
0,False,True,False,True,2025,10,20
1,False,False,True,True,2025,10,20
2,True,False,False,True,2025,10,20
3,False,True,False,True,2022,12,31
4,False,False,True,True,2022,12,31

In [38]:
y = gas_prices_df["price"].copy()
y.head()
# print("Probability:", probability[0][1])

0    1899
1    2189
2    1649
3    1739
4    2009
Name: price, dtype: int64

In [39]:
# new_price = pd.DataFrame({
#     "gas_station_id": [377],
#     "fuel_type": ["Euro95 E10"],
#     "created_at": ["2026-01-20"]
# })
# new_price = pd.get_dummies(new_price, columns=["fuel_type", "gas_station_id"])
#
# new_price["created_at"] = pd.to_datetime(new_price["created_at"])
# new_price["year"] = new_price["created_at"].dt.year
# new_price["month"] = new_price["created_at"].dt.month
# new_price["day"] = new_price["created_at"].dt.day
# new_price = new_price.drop(columns=["created_at"])
# new_price.head()

In [40]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

model = LinearRegression()
model.fit(x_train, y_train)

accuracy = model.score(x_test, y_test)
print(f"Model accuracy: {accuracy*100:.2f}%")

(2388, 7)
(597, 7)
(2388,)
(597,)
Model accuracy: 87.58%

In [82]:
model_features = model.feature_names_in_

new_price = pd.DataFrame({
    "gas_station_id": [377],
    "fuel_type": ['Euro95 E10'],
    "created_at": ["2026-03-20"]
})
new_price = pd.get_dummies(new_price, columns=["fuel_type", "gas_station_id"])

new_price["created_at"] = pd.to_datetime(new_price["created_at"])
new_price["year"] = new_price["created_at"].dt.year
new_price["month"] = new_price["created_at"].dt.month
new_price["day"] = new_price["created_at"].dt.day
new_price = new_price.reindex(columns=model_features, fill_value=False)
new_price.head()

prediction = model.predict(new_price)

print("Prediction:", prediction[0])

Prediction: 1919.9409299496729