In [12]:
import pandas as pd
from sqlalchemy import create_engine

db_user = 'postgres'
db_password = 'postgres'
db_host = 'localhost'
db_port = '5432'
db_name = 'puzzle'

engine = create_engine(f'postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}')

In [13]:
gas_stations_query = """
SELECT * FROM gas_stations
ORDER BY random()
LIMIT 5;
"""
gas_stations_df = pd.read_sql(gas_stations_query, engine)
gas_stations_df.head()

,id,company_name,site,country,city,street_name,house_number,postal_code,lat,lng,is_favorite,created_at,updated_at,location,external_id
0,1153,de-haan,https://tankstation.nl/tankstation/haan-expres...,NL,Lith,Brouwerspad,22,5397 GG,51.808392,5.429383,False,2025-10-25 18:16:43,2025-10-25 18:16:43,0101000020E610000028D9A326B0B71540B6AB466579E7...,6919
1,1089,aral,https://api.tankstelle.aral.de/api/v3/stations...,DE,Dorsten,Duelmener Straße,8,46286,51.721643,7.012792,False,2025-10-24 22:17:37,2025-10-24 22:17:37,0101000020E61000000B9A9658190D1C4094313ECC5EDC...,NaN
2,788,tango,https://www.tango.nl/stations/tango-den-haag-p...,NL,Den Haag,Prinses Beatrixlaan,900,2595 BP,52.076840,4.339320,False,2023-01-09 15:48:43,2025-10-17 23:04:37,0101000020E6100000CF83BBB3765B11402783A3E4D509...,202356
3,1133,bp,https://tankstation.nl/tankstation/bp-het-veen/,NL,Heerde,Rijksweg A50,1,8181 MH,52.396223,6.013967,False,2025-10-25 18:16:42,2025-10-25 18:16:42,0101000020E61000002AB59C754D0E1840E2220971B732...,6899
4,914,aral,https://api.tankstelle.aral.de/api/v3/stations...,DE,Aurich,Emderstr.,19,26603,53.470888,7.467794,False,2024-11-07 15:16:16,2025-07-29 01:25:19,0101000020E6100000620FED6305DF1D40180AD80E46BC...,NaN

In [14]:
gas_stations_df.describe()

,id,lat,lng,created_at,updated_at
count,5.00000,5.000000,5.000000,5,5
mean,1015.40000,52.294797,6.052651,2025-01-24 03:35:12.200000,2025-10-06 07:04:11.600000
min,788.00000,51.721643,4.339320,2023-01-09 15:48:43,2025-07-29 01:25:19
25%,914.00000,51.808392,5.429383,2024-11-07 15:16:16,2025-10-17 23:04:37
50%,1089.00000,52.076840,6.013967,2025-10-24 22:17:37,2025-10-24 22:17:37
75%,1133.00000,52.396223,7.012792,2025-10-25 18:16:42,2025-10-25 18:16:42
max,1153.00000,53.470888,7.467794,2025-10-25 18:16:43,2025-10-25 18:16:43
std,158.25075,0.708180,1.249996,NaN,NaN

In [15]:
gas_prices_query = """
SELECT * FROM gas_prices
ORDER BY random()
LIMIT 5;
"""
gas_prices_df = pd.read_sql(gas_prices_query, engine)
gas_prices_df.head()

,id,gas_station_id,fuel_type,price,created_at,updated_at
0,2619596,13,Euro95 E10,1889,2025-04-22 18:01:05,2025-04-22 18:01:05
1,3162501,480,Euro95 E10,1471,2025-09-27 18:00:07,2025-09-27 18:00:07
2,49986,832,Euro95 E10,1699,2023-01-16 18:02:16,2023-01-16 18:02:16
3,1381266,180,Diesel B7,1699,2024-04-21 18:02:43,2024-04-21 18:02:43
4,1649672,146,Superplus 98 E5,2239,2024-07-01 18:02:16,2024-07-01 18:02:16

In [16]:
gas_prices_df.describe()

,id,gas_station_id,price,created_at,updated_at
count,5.000000e+00,5.000000,5.000000,5,5
mean,1.772604e+06,330.200000,1799.400000,2024-07-30 18:01:41.400000,2024-07-30 18:01:41.400000
min,4.998600e+04,13.000000,1471.000000,2023-01-16 18:02:16,2023-01-16 18:02:16
25%,1.381266e+06,146.000000,1699.000000,2024-04-21 18:02:43,2024-04-21 18:02:43
50%,1.649672e+06,180.000000,1699.000000,2024-07-01 18:02:16,2024-07-01 18:02:16
75%,2.619596e+06,480.000000,1889.000000,2025-04-22 18:01:05,2025-04-22 18:01:05
max,3.162501e+06,832.000000,2239.000000,2025-09-27 18:00:07,2025-09-27 18:00:07
std,1.202589e+06,328.385749,286.916016,NaN,NaN

In [17]:
# train the model
# Load all data
gas_stations_query = """
SELECT * FROM gas_stations WHERE id = 377;
"""
gas_stations_df = pd.read_sql(gas_stations_query, engine)
gas_stations_df.head()

,id,company_name,site,country,city,street_name,house_number,postal_code,lat,lng,is_favorite,created_at,updated_at,location,external_id
0,377,tango,https://www.tango.nl/stations/tango-haelen,NL,HAELEN,Windmolenbosweg,2,6081 PE,51.222206,5.951285,True,2022-12-30 15:35:36,2025-10-17 23:02:56,0101000020E61000002CA688C21DCE17401F7B6242719C...,202220

In [23]:
gas_prices_query = """
SELECT * FROM gas_prices WHERE gas_station_id IN (377, 378);
"""
gas_prices_df = pd.read_sql(gas_prices_query, engine)
print(gas_prices_df.count())
gas_prices_df.head()

id                6124
gas_station_id    6124
fuel_type         6124
price             6124
created_at        6124
updated_at        6124
dtype: int64

,id,gas_station_id,fuel_type,price,created_at,updated_at
0,3236542,378,Diesel B7,1635,2025-10-20 18:00:03,2025-10-20 18:00:03
1,3236543,378,Euro95 E10,1588,2025-10-20 18:00:03,2025-10-20 18:00:03
2,3236544,378,Superplus 98 E5,1699,2025-10-20 18:00:03,2025-10-20 18:00:03
3,3821818,378,Diesel B7,1626,2026-01-21 18:00:04,2026-01-21 18:00:04
4,3821819,378,Euro95 E10,1527,2026-01-21 18:00:04,2026-01-21 18:00:04

In [19]:
x = gas_prices_df[["gas_station_id", "fuel_type", "created_at"]].copy()
x = pd.get_dummies(x, columns=["fuel_type", "gas_station_id"])

x["created_at"] = pd.to_datetime(x["created_at"])
x["year"] = x["created_at"].dt.year
x["month"] = x["created_at"].dt.month
x["day"] = x["created_at"].dt.day
x = x.drop(columns=["created_at"])

x.head()

,fuel_type_Diesel B7,fuel_type_Euro95 E10,fuel_type_Superplus 98 E5,gas_station_id_377,gas_station_id_378,year,month,day
0,True,False,False,False,True,2025,10,20
1,False,True,False,False,True,2025,10,20
2,False,False,True,False,True,2025,10,20
3,True,False,False,False,True,2026,1,21
4,False,True,False,False,True,2026,1,21

In [24]:
y = gas_prices_df["price"].copy()
y.head()

0    1635
1    1588
2    1699
3    1626
4    1527
Name: price, dtype: int64

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

model = LinearRegression()
model.fit(x_train, y_train)

accuracy = model.score(x_test, y_test)
print(f"Model accuracy: {accuracy*100:.2f}%")

(4899, 8)
(1225, 8)
(4899,)
(1225,)
Model accuracy: 67.66%

In [22]:
model_features = model.feature_names_in_

new_price = pd.DataFrame({
    "gas_station_id": [377],
    "fuel_type": ['Euro95 E10'],
    "created_at": ["2026-03-20"]
})
new_price = pd.get_dummies(new_price, columns=["fuel_type", "gas_station_id"])

new_price["created_at"] = pd.to_datetime(new_price["created_at"])
new_price["year"] = new_price["created_at"].dt.year
new_price["month"] = new_price["created_at"].dt.month
new_price["day"] = new_price["created_at"].dt.day
new_price = new_price.reindex(columns=model_features, fill_value=False)
new_price.head()

prediction = model.predict(new_price)

print("Prediction:", prediction[0])

Prediction: 1810.1263523729722