In [13]:
import pandas as pd
from sqlalchemy import create_engine

db_user = 'postgres'
db_password = 'postgres'
db_host = 'localhost'
db_port = '5432'
db_name = 'puzzle'

engine = create_engine(f'postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}')

In [14]:
gas_stations_query = """
SELECT * FROM gas_stations
ORDER BY random()
LIMIT 5;
"""
gas_stations_df = pd.read_sql(gas_stations_query, engine)
gas_stations_df.head()

,id,company_name,site,country,city,street_name,house_number,postal_code,lat,lng,is_favorite,created_at,updated_at,location,external_id
0,1155,de-haan,https://tankstation.nl/tankstation/haan-expres...,NL,Mijnsheerenland,Raadhuislaan,48,3271 BT,51.800800,4.480198,False,2025-10-25 18:16:43,2025-10-25 18:16:43,0101000020E6100000D494DC0CB9EB1140F2B3909D80E6...,6921
1,1101,esso-express,https://tankstation.nl/tankstation/esso-expres...,NL,Heemstede,Cruquiusweg,1,2102 LS,52.343810,4.629023,False,2025-10-25 18:16:42,2025-10-25 18:16:42,0101000020E6100000E09EE2B51E841240DE4C9DF6012C...,6688
2,202,tinq,https://www.tinq.nl/tankstations/rheden-arnhem...,NL,Rheden,Arnhemseweg,7,6991 DK,52.005670,6.032266,False,2022-12-30 15:35:34,2023-01-09 15:46:56,0101000020E6100000EF13515D0A211840D78A36C7B900...,NaN
3,866,aral,https://api.tankstelle.aral.de/api/v3/stations...,DE,Uedem,Molkerei-/Kervenheimer St,,47589,51.658244,6.275204,False,2024-05-14 11:01:12,2025-07-29 01:25:19,0101000020E6100000DDE9CE13CF191940E564E25641D4...,NaN
4,58,tinq,https://www.tinq.nl/tankstations/doetinchem-eu...,NL,Doetinchem,Europaweg,30,7007 GJ,51.950351,6.274029,False,2022-12-30 15:35:32,2023-01-09 15:46:56,0101000020E610000004A678019B18194070DBAD1BA5F9...,NaN

In [15]:
gas_stations_df.describe()

,id,lat,lng,created_at,updated_at
count,5.000000,5.000000,5.000000,5,5
mean,676.400000,51.951775,5.538144,2024-05-25 20:33:08.600000,2024-08-25 23:30:31.200000
min,58.000000,51.658244,4.480198,2022-12-30 15:35:32,2023-01-09 15:46:56
25%,202.000000,51.800800,4.629023,2022-12-30 15:35:34,2023-01-09 15:46:56
50%,866.000000,51.950351,6.032266,2024-05-14 11:01:12,2025-07-29 01:25:19
75%,1101.000000,52.005670,6.274029,2025-10-25 18:16:42,2025-10-25 18:16:42
max,1155.000000,52.343810,6.275204,2025-10-25 18:16:43,2025-10-25 18:16:43
std,513.021734,0.257659,0.904805,NaN,NaN

In [16]:
gas_prices_query = """
SELECT * FROM gas_prices
ORDER BY random()
LIMIT 5;
"""
gas_prices_df = pd.read_sql(gas_prices_query, engine)
gas_prices_df.head()

,id,gas_station_id,fuel_type,price,created_at,updated_at
0,1290650,152,Superplus 98 E5,2269,2024-03-28 18:02:40,2024-03-28 18:02:40
1,3920248,830,Euro95 E5,1759,2026-02-07 18:03:27,2026-02-07 18:03:27
2,732378,546,Superplus 98 E5,1979,2023-10-31 18:00:09,2023-10-31 18:00:09
3,1463487,131,Euro95 E10,2009,2024-05-13 18:02:08,2024-05-13 18:02:08
4,3435626,489,Diesel B7,1646,2025-11-20 18:00:07,2025-11-20 18:00:07

In [17]:
gas_prices_df.describe()

,id,gas_station_id,price,created_at,updated_at
count,5.000000e+00,5.000000,5.000000,5,5
mean,2.168478e+06,429.600000,1932.400000,2024-11-19 18:01:42.200000,2024-11-19 18:01:42.200000
min,7.323780e+05,131.000000,1646.000000,2023-10-31 18:00:09,2023-10-31 18:00:09
25%,1.290650e+06,152.000000,1759.000000,2024-03-28 18:02:40,2024-03-28 18:02:40
50%,1.463487e+06,489.000000,1979.000000,2024-05-13 18:02:08,2024-05-13 18:02:08
75%,3.435626e+06,546.000000,2009.000000,2025-11-20 18:00:07,2025-11-20 18:00:07
max,3.920248e+06,830.000000,2269.000000,2026-02-07 18:03:27,2026-02-07 18:03:27
std,1.414597e+06,293.096059,241.573591,NaN,NaN

In [18]:
# train the model
# Load all data
gas_stations_query = """
SELECT * FROM gas_stations WHERE id = 377;
"""
gas_stations_df = pd.read_sql(gas_stations_query, engine)
gas_stations_df.head()

,id,company_name,site,country,city,street_name,house_number,postal_code,lat,lng,is_favorite,created_at,updated_at,location,external_id
0,377,tango,https://www.tango.nl/stations/tango-haelen,NL,HAELEN,Windmolenbosweg,2,6081 PE,51.222206,5.951285,True,2022-12-30 15:35:36,2025-10-17 23:02:56,0101000020E61000002CA688C21DCE17401F7B6242719C...,202220

In [19]:
gas_prices_query = """
SELECT * FROM gas_prices WHERE gas_station_id = 377;
"""
gas_prices_df = pd.read_sql(gas_prices_query, engine)
print(gas_prices_df.count())
gas_prices_df.head()

id                2985
gas_station_id    2985
fuel_type         2985
price             2985
created_at        2985
updated_at        2985
dtype: int64

,id,gas_station_id,fuel_type,price,created_at,updated_at
0,3237268,377,Euro95 E10,1899,2025-10-20 18:00:13,2025-10-20 18:00:13
1,3237269,377,Superplus 98 E5,2189,2025-10-20 18:00:13,2025-10-20 18:00:13
2,3237270,377,Diesel B7,1649,2025-10-20 18:00:13,2025-10-20 18:00:13
3,1132,377,Euro95 E10,1739,2022-12-31 18:00:04,2022-12-31 18:00:04
4,1133,377,Superplus 98 E5,2009,2022-12-31 18:00:04,2022-12-31 18:00:04

In [20]:
x = gas_prices_df[["gas_station_id", "fuel_type", "created_at"]].copy()
x = pd.get_dummies(x, columns=["fuel_type", "gas_station_id"])

x["created_at"] = pd.to_datetime(x["created_at"])
x["year"] = x["created_at"].dt.year
x["month"] = x["created_at"].dt.month
x["day"] = x["created_at"].dt.day
x = x.drop(columns=["created_at"])

x.head()

,fuel_type_Diesel B7,fuel_type_Euro95 E10,fuel_type_Superplus 98 E5,gas_station_id_377,year,month,day
0,False,True,False,True,2025,10,20
1,False,False,True,True,2025,10,20
2,True,False,False,True,2025,10,20
3,False,True,False,True,2022,12,31
4,False,False,True,True,2022,12,31

In [21]:
y = gas_prices_df["price"].copy()
y.head()

0    1899
1    2189
2    1649
3    1739
4    2009
Name: price, dtype: int64

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

model = LinearRegression()
model.fit(x_train, y_train)

accuracy = model.score(x_test, y_test)
print(f"Model accuracy: {accuracy*100:.2f}%")

(2388, 7)
(597, 7)
(2388,)
(597,)
Model accuracy: 86.82%

In [23]:
model_features = model.feature_names_in_

new_price = pd.DataFrame({
    "gas_station_id": [377],
    "fuel_type": ['Euro95 E10'],
    "created_at": ["2026-03-20"]
})
new_price = pd.get_dummies(new_price, columns=["fuel_type", "gas_station_id"])

new_price["created_at"] = pd.to_datetime(new_price["created_at"])
new_price["year"] = new_price["created_at"].dt.year
new_price["month"] = new_price["created_at"].dt.month
new_price["day"] = new_price["created_at"].dt.day
new_price = new_price.reindex(columns=model_features, fill_value=False)
new_price.head()

prediction = model.predict(new_price)

print("Prediction:", prediction[0])

Prediction: 1922.001445987782